/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmployeeManager;
import admin.*;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.*;
import java.io.ByteArrayOutputStream;
import java.io.FileInputStream;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author dhiru
 */
public class addemployee extends javax.swing.JFrame {

    /**
     * Creates new form addemployee
     */
    String filename= null;
    byte[] person_image = null;
    public addemployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        designation = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        choose = new javax.swing.JButton();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        transgender = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        displayusername = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        maritalstatus = new javax.swing.JComboBox<>();
        dateofjoining = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        dateofbirth = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Employee Details");
        setMaximumSize(new java.awt.Dimension(740, 560));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 63, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Designation");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 147, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Gender");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 186, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Date Of Birth");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 102, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Date Of Joining");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 336, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Marital Status");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 381, -1, -1));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 223, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Employee Details");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));
        getContentPane().add(designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 142, 345, -1));

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 82, -1));

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 73, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 58, 345, -1));

        choose.setText("Choose Image");
        choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseActionPerformed(evt);
            }
        });
        getContentPane().add(choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));

        buttonGroup1.add(male);
        male.setText("Male");
        getContentPane().add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        buttonGroup1.add(female);
        female.setText("Female");
        getContentPane().add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        buttonGroup1.add(transgender);
        transgender.setText("Transgender");
        transgender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transgenderActionPerformed(evt);
            }
        });
        getContentPane().add(transgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, -1));

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setText("Salary");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        salary.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 340, -1));

        displayusername.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        getContentPane().add(displayusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 250, 20));

        img.setBackground(new java.awt.Color(182, 200, 253));
        img.setForeground(new java.awt.Color(174, 213, 250));
        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeManager/trombone.jpg"))); // NOI18N
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 160, 170));

        maritalstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Marital Status", "Single", "Married", "Divorced" }));
        getContentPane().add(maritalstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 210, -1));

        dateofjoining.setDateFormatString("YYYY-MM-dd");
        getContentPane().add(dateofjoining, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 220, -1));

        address.setColumns(20);
        address.setRows(5);
        jScrollPane2.setViewportView(address);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 340, -1));

        dateofbirth.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(dateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 220, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmployeeManager/Employee-Management-Systems.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -10, 860, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Employee field = new Employee();
        field.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseActionPerformed
        
        JFileChooser choose= new JFileChooser();
        choose.showOpenDialog(null);
        File f = choose.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageicon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(),img.getHeight(),Image.SCALE_SMOOTH));
        img.setIcon(imageicon);
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf =new byte[1024];
            for (int readNum;(readNum=fis.read(buf))!=-1;)
            {
                bos.write(buf,0,readNum);
            }
            person_image=bos.toByteArray();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_chooseActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String gender = null;
        
        try{  
        Class.forName("com.mysql.jdbc.Driver");  
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/empmanagement?autoReconnect=true&useSSL=false","root","login");  
        //here adminlogin is database name, root is username and "login" is the password  
        String query = "INSERT INTO empdetails(name,dateofbirth,designation,gender,address,dateofjoining,maritalstatus,photo,salary) VALUES(?,?,?,?,?,?,?,?,?)";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, name.getText());
        pst.setString(2, ((JTextField)dateofbirth.getDateEditor().getUiComponent()).getText());
        pst.setString(3, designation.getText());
        
        if(male.isSelected())
        {
            gender = "Male";
        }
        if(female.isSelected())
        {
            gender = "Female";
        
        }
        if(transgender.isSelected())
        {
            gender = "Transgender";
        }
        pst.setString(4, gender);
        pst.setString(5, address.getText());
        pst.setString(6, ((JTextField)dateofjoining.getDateEditor().getUiComponent()).getText());
        String maritalStatus;
        maritalStatus = maritalstatus.getSelectedItem().toString();
        pst.setString(7, maritalStatus);
        pst.setBytes(8, person_image);
        pst.setString(9, salary.getText());
        pst.executeUpdate();
        System.out.println("successfull");
    }
         catch(Exception e){ System.out.println(e);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void transgenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transgenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transgenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton choose;
    private com.toedter.calendar.JDateChooser dateofbirth;
    private com.toedter.calendar.JDateChooser dateofjoining;
    private javax.swing.JTextField designation;
    public static javax.swing.JLabel displayusername;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel img;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton male;
    private javax.swing.JComboBox<String> maritalstatus;
    private javax.swing.JTextField name;
    private javax.swing.JTextField salary;
    private javax.swing.JRadioButton transgender;
    // End of variables declaration//GEN-END:variables
}
